"""sagat checkpoints and nasa tlx

Revision ID: cdee813c8dce
Revises: 3f9ac5e34f47
Create Date: 2026-08-12 14:46:40.380363

"""

import sqlalchemy as sa
from alembic import op

revision: str = "cdee813c8dce"
down_revision: str | None = "3f9ac5e34f47"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nasa_tlx_responses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("values_json", sa.JSON(), nullable=False),
        sa.Column("raw_tlx_score", sa.Float(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_nasa_tlx_responses_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nasa_tlx_responses")),
        sa.UniqueConstraint("session_id", name=op.f("uq_nasa_tlx_responses_session_id")),
    )
    op.create_table(
        "sagat_checkpoints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("checkpoint_code", sa.String(length=64), nullable=False),
        sa.Column("triggered_sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("answers_deadline_sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("earlier_metrics_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_sagat_checkpoints_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sagat_checkpoints")),
        sa.UniqueConstraint(
            "session_id", "checkpoint_code", name=op.f("uq_sagat_checkpoints_session_id_checkpoint_code")
        ),
    )
    with op.batch_alter_table("sagat_checkpoints", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sagat_checkpoints_session_id"), ["session_id"], unique=False)

    op.create_table(
        "sagat_answers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=36), nullable=False),
        sa.Column("question_code", sa.String(length=64), nullable=False),
        sa.Column("answer_json", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkpoint_id"],
            ["sagat_checkpoints.id"],
            name=op.f("fk_sagat_answers_checkpoint_id_sagat_checkpoints"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sagat_answers")),
        sa.UniqueConstraint(
            "checkpoint_id", "question_code", name=op.f("uq_sagat_answers_checkpoint_id_question_code")
        ),
    )
    with op.batch_alter_table("sagat_answers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sagat_answers_checkpoint_id"), ["checkpoint_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sagat_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sagat_answers_checkpoint_id"))

    op.drop_table("sagat_answers")
    with op.batch_alter_table("sagat_checkpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sagat_checkpoints_session_id"))

    op.drop_table("sagat_checkpoints")
    op.drop_table("nasa_tlx_responses")
    # ### end Alembic commands ###
