"""catalog: installation, equipment, tags, topology

Revision ID: 8f0b3305e936
Revises: 68038013c8c8
Create Date: 2026-08-10 18:38:40.622118

"""

import sqlalchemy as sa
from alembic import op

revision: str = "8f0b3305e936"
down_revision: str | None = "68038013c8c8"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installation_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("installation_code", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installation_versions")),
        sa.UniqueConstraint(
            "installation_code", "version", name=op.f("uq_installation_versions_installation_code_version")
        ),
    )
    op.create_table(
        "equipment",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("installation_version_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("equipment_type", sa.String(length=64), nullable=False),
        sa.Column("parent_equipment_id", sa.String(length=36), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["installation_version_id"],
            ["installation_versions.id"],
            name=op.f("fk_equipment_installation_version_id_installation_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_equipment_id"],
            ["equipment.id"],
            name=op.f("fk_equipment_parent_equipment_id_equipment"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment")),
        sa.UniqueConstraint(
            "installation_version_id", "code", name=op.f("uq_equipment_installation_version_id_code")
        ),
    )
    with op.batch_alter_table("equipment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_equipment_installation_version_id"), ["installation_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_equipment_parent_equipment_id"), ["parent_equipment_id"], unique=False
        )

    op.create_table(
        "process_tags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("equipment_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("value_type", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("normal_min", sa.Float(), nullable=True),
        sa.Column("normal_max", sa.Float(), nullable=True),
        sa.Column("warning_min", sa.Float(), nullable=True),
        sa.Column("warning_max", sa.Float(), nullable=True),
        sa.Column("critical_min", sa.Float(), nullable=True),
        sa.Column("critical_max", sa.Float(), nullable=True),
        sa.Column("visible_to_operator", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_process_tags_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_tags")),
        sa.UniqueConstraint("equipment_id", "code", name=op.f("uq_process_tags_equipment_id_code")),
    )
    with op.batch_alter_table("process_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_process_tags_code"), ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_process_tags_equipment_id"), ["equipment_id"], unique=False)

    op.create_table(
        "topology_edges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("installation_version_id", sa.String(length=36), nullable=False),
        sa.Column("from_equipment_id", sa.String(length=36), nullable=False),
        sa.Column("to_equipment_id", sa.String(length=36), nullable=False),
        sa.Column("stream_code", sa.String(length=64), nullable=False),
        sa.Column("branch_no", sa.Integer(), nullable=True),
        sa.Column("stream_type", sa.String(length=64), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_equipment_id"],
            ["equipment.id"],
            name=op.f("fk_topology_edges_from_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["installation_version_id"],
            ["installation_versions.id"],
            name=op.f("fk_topology_edges_installation_version_id_installation_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_equipment_id"],
            ["equipment.id"],
            name=op.f("fk_topology_edges_to_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topology_edges")),
    )
    with op.batch_alter_table("topology_edges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_topology_edges_installation_version_id"), ["installation_version_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topology_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topology_edges_installation_version_id"))

    op.drop_table("topology_edges")
    with op.batch_alter_table("process_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_process_tags_equipment_id"))
        batch_op.drop_index(batch_op.f("ix_process_tags_code"))

    op.drop_table("process_tags")
    with op.batch_alter_table("equipment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_equipment_parent_equipment_id"))
        batch_op.drop_index(batch_op.f("ix_equipment_installation_version_id"))

    op.drop_table("equipment")
    op.drop_table("installation_versions")
    # ### end Alembic commands ###
