"""expected action rules unique by order

Revision ID: 4b38576b2205
Revises: 942f647ae7ac
Create Date: 2026-08-10 19:11:00.079109

"""

from alembic import op

revision: str = "4b38576b2205"
down_revision: str | None = "942f647ae7ac"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expected_action_rules", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_expected_action_rules_scenario_version_id_situation_code_action_type"),
            type_="unique",
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_expected_action_rules_scenario_version_id_situation_code_order_no"),
            ["scenario_version_id", "situation_code", "order_no"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expected_action_rules", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_expected_action_rules_scenario_version_id_situation_code_order_no"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_expected_action_rules_scenario_version_id_situation_code_action_type"),
            ["scenario_version_id", "situation_code", "action_type"],
        )

    # ### end Alembic commands ###
