"""session alarms

Revision ID: a58dd63500a6
Revises: 68968e1d5b07
Create Date: 2026-08-11 13:53:01.310462

"""

import sqlalchemy as sa
from alembic import op

revision: str = "a58dd63500a6"
down_revision: str | None = "68968e1d5b07"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_alarms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("alarm_rule_id", sa.String(length=36), nullable=True),
        sa.Column("alarm_code", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=64), nullable=False),
        sa.Column("equipment_code", sa.String(length=64), nullable=False),
        sa.Column("message", sa.String(length=200), nullable=False),
        sa.Column("ack_required", sa.Boolean(), nullable=False),
        sa.Column("is_nuisance", sa.Boolean(), nullable=False),
        sa.Column("started_sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("acknowledged_sim_time_ms", sa.Integer(), nullable=True),
        sa.Column("cleared_sim_time_ms", sa.Integer(), nullable=True),
        sa.Column("acknowledged_by_operator_id", sa.String(), nullable=True),
        sa.Column("source_event_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["alarm_rule_id"],
            ["alarm_rules.id"],
            name=op.f("fk_session_alarms_alarm_rule_id_alarm_rules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_alarms_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["session_events.id"],
            name=op.f("fk_session_alarms_source_event_id_session_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_alarms")),
    )
    with op.batch_alter_table("session_alarms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_alarms_alarm_code"), ["alarm_code"], unique=False)
        batch_op.create_index(batch_op.f("ix_session_alarms_session_id"), ["session_id"], unique=False)
        batch_op.create_index(
            "ix_session_alarms_session_started", ["session_id", "started_sim_time_ms"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_alarms", schema=None) as batch_op:
        batch_op.drop_index("ix_session_alarms_session_started")
        batch_op.drop_index(batch_op.f("ix_session_alarms_session_id"))
        batch_op.drop_index(batch_op.f("ix_session_alarms_alarm_code"))

    op.drop_table("session_alarms")
    # ### end Alembic commands ###
