"""training sessions, events, snapshots and command requests

Revision ID: 2d52a15cbb5d
Revises: 4b38576b2205
Create Date: 2026-08-10 19:35:23.064298

"""

import sqlalchemy as sa
from alembic import op

revision: str = "2d52a15cbb5d"
down_revision: str | None = "4b38576b2205"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "training_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("operator_id", sa.String(length=64), nullable=False),
        sa.Column("instructor_id", sa.String(), nullable=True),
        sa.Column("scenario_version_id", sa.String(length=36), nullable=False),
        sa.Column("scenario_level_id", sa.String(length=36), nullable=False),
        sa.Column("scoring_policy_version_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("last_sequence_no", sa.Integer(), nullable=False),
        sa.Column("current_stage_code", sa.String(length=64), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("hidden_runtime_config_json", sa.JSON(), nullable=False),
        sa.Column("final_outcome", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("paused_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_level_id"],
            ["scenario_levels.id"],
            name=op.f("fk_training_sessions_scenario_level_id_scenario_levels"),
        ),
        sa.ForeignKeyConstraint(
            ["scenario_version_id"],
            ["scenario_versions.id"],
            name=op.f("fk_training_sessions_scenario_version_id_scenario_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["scoring_policy_version_id"],
            ["scoring_policy_versions.id"],
            name=op.f("fk_training_sessions_scoring_policy_version_id_scoring_policy_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_sessions")),
    )
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_training_sessions_active", ["status"], unique=False)
        batch_op.create_index(
            "ix_training_sessions_operator_started", ["operator_id", "started_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_training_sessions_scenario_level_id"), ["scenario_level_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_training_sessions_scenario_version_id"), ["scenario_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_training_sessions_scoring_policy_version_id"),
            ["scoring_policy_version_id"],
            unique=False,
        )

    op.create_table(
        "command_requests",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("command", sa.String(length=64), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_command_requests_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("pk_command_requests")),
    )
    with op.batch_alter_table("command_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_command_requests_session_id"), ["session_id"], unique=False)

    op.create_table(
        "process_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("stage_code", sa.String(length=64), nullable=False),
        sa.Column("visible_values_json", sa.JSON(), nullable=False),
        sa.Column("derived_values_json", sa.JSON(), nullable=False),
        sa.Column("internal_state_json", sa.JSON(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_process_snapshots_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_snapshots")),
        sa.UniqueConstraint(
            "session_id", "sequence_no", name=op.f("uq_process_snapshots_session_id_sequence_no")
        ),
        sa.UniqueConstraint(
            "session_id", "sim_time_ms", name=op.f("uq_process_snapshots_session_id_sim_time_ms")
        ),
    )
    with op.batch_alter_table("process_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_process_snapshots_session_id"), ["session_id"], unique=False)
        batch_op.create_index(
            "ix_process_snapshots_session_sim_time", ["session_id", "sim_time_ms"], unique=False
        )

    op.create_table(
        "session_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("causation_id", sa.String(), nullable=True),
        sa.Column("correlation_id", sa.String(), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_events_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_events")),
        sa.UniqueConstraint(
            "session_id", "sequence_no", name=op.f("uq_session_events_session_id_sequence_no")
        ),
    )
    with op.batch_alter_table("session_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_events_session_id"), ["session_id"], unique=False)
        batch_op.create_index(
            "ix_session_events_session_sequence", ["session_id", "sequence_no"], unique=False
        )

    op.create_table(
        "session_stage_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("stage_code", sa.String(length=64), nullable=False),
        sa.Column("entered_sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("exited_sim_time_ms", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("transition_reason_event_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_stage_history_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transition_reason_event_id"],
            ["session_events.id"],
            name=op.f("fk_session_stage_history_transition_reason_event_id_session_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_stage_history")),
    )
    with op.batch_alter_table("session_stage_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_session_stage_history_session_entered", ["session_id", "entered_sim_time_ms"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_session_stage_history_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_stage_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_stage_history_session_id"))
        batch_op.drop_index("ix_session_stage_history_session_entered")

    op.drop_table("session_stage_history")
    with op.batch_alter_table("session_events", schema=None) as batch_op:
        batch_op.drop_index("ix_session_events_session_sequence")
        batch_op.drop_index(batch_op.f("ix_session_events_session_id"))

    op.drop_table("session_events")
    with op.batch_alter_table("process_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_process_snapshots_session_sim_time")
        batch_op.drop_index(batch_op.f("ix_process_snapshots_session_id"))

    op.drop_table("process_snapshots")
    with op.batch_alter_table("command_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_command_requests_session_id"))

    op.drop_table("command_requests")
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_sessions_scoring_policy_version_id"))
        batch_op.drop_index(batch_op.f("ix_training_sessions_scenario_version_id"))
        batch_op.drop_index(batch_op.f("ix_training_sessions_scenario_level_id"))
        batch_op.drop_index("ix_training_sessions_operator_started")
        batch_op.drop_index("ix_training_sessions_active")

    op.drop_table("training_sessions")
    # ### end Alembic commands ###
