"""session runtime state

Revision ID: 63eb50e38cdf
Revises: 2d52a15cbb5d
Create Date: 2026-08-11 13:34:11.783864

"""

import sqlalchemy as sa
from alembic import op

revision: str = "63eb50e38cdf"
down_revision: str | None = "2d52a15cbb5d"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # server_default обязателен: без него добавление NOT NULL-колонки падает на
    # существующих строках. Пустой объект означает «двойник ещё не рассчитан».
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("runtime_state_json", sa.JSON(), nullable=False, server_default=sa.text("'{}'"))
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("training_sessions", schema=None) as batch_op:
        batch_op.drop_column("runtime_state_json")

    # ### end Alembic commands ###
