"""scores and reports

Revision ID: aeab25215eb7
Revises: cdee813c8dce
Create Date: 2026-08-12 15:02:32.587626

"""

import sqlalchemy as sa
from alembic import op

revision: str = "aeab25215eb7"
down_revision: str | None = "cdee813c8dce"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_reports",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("report_version", sa.Integer(), nullable=False),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_reports_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_session_reports")),
    )
    op.create_table(
        "session_scores",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("scoring_policy_version_id", sa.String(length=36), nullable=False),
        sa.Column("safety_score", sa.Float(), nullable=False),
        sa.Column("action_correctness_score", sa.Float(), nullable=False),
        sa.Column("process_stability_score", sa.Float(), nullable=False),
        sa.Column("reaction_score", sa.Float(), nullable=False),
        sa.Column("resultiveness_score", sa.Float(), nullable=False),
        sa.Column("situation_awareness_score", sa.Float(), nullable=False),
        sa.Column("recovery_time_ms", sa.Integer(), nullable=True),
        sa.Column("raw_nasa_tlx", sa.Float(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scoring_policy_version_id"],
            ["scoring_policy_versions.id"],
            name=op.f("fk_session_scores_scoring_policy_version_id_scoring_policy_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_session_scores_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_session_scores")),
    )
    op.create_table(
        "score_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=64), nullable=False),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("rule_code", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("source_event_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_score_events_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["session_events.id"],
            name=op.f("fk_score_events_source_event_id_session_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_events")),
    )
    with op.batch_alter_table("score_events", schema=None) as batch_op:
        batch_op.create_index("ix_score_events_session_dimension", ["session_id", "dimension"], unique=False)
        batch_op.create_index(batch_op.f("ix_score_events_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_events_session_id"))
        batch_op.drop_index("ix_score_events_session_dimension")

    op.drop_table("score_events")
    op.drop_table("session_scores")
    op.drop_table("session_reports")
    # ### end Alembic commands ###
