"""operator actions

Revision ID: 68968e1d5b07
Revises: 63eb50e38cdf
Create Date: 2026-08-11 13:38:43.824485

"""

import sqlalchemy as sa
from alembic import op

revision: str = "68968e1d5b07"
down_revision: str | None = "63eb50e38cdf"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("target_code", sa.String(length=64), nullable=False),
        sa.Column("requested_value_json", sa.JSON(), nullable=False),
        sa.Column("before_state_json", sa.JSON(), nullable=False),
        sa.Column("after_state_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("classification", sa.String(), nullable=True),
        sa.Column("evaluation_pending_until_ms", sa.Integer(), nullable=True),
        sa.Column("expected_rule_id", sa.String(length=36), nullable=True),
        sa.Column("requires_verification", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["expected_rule_id"],
            ["expected_action_rules.id"],
            name=op.f("fk_operator_actions_expected_rule_id_expected_action_rules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_operator_actions_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_actions")),
        sa.UniqueConstraint("request_id", name=op.f("uq_operator_actions_request_id")),
    )
    with op.batch_alter_table("operator_actions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_operator_actions_session_id"), ["session_id"], unique=False)
        batch_op.create_index(
            "ix_operator_actions_session_sim_time", ["session_id", "sim_time_ms"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_operator_actions_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("operator_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_operator_actions_status"))
        batch_op.drop_index("ix_operator_actions_session_sim_time")
        batch_op.drop_index(batch_op.f("ix_operator_actions_session_id"))

    op.drop_table("operator_actions")
    # ### end Alembic commands ###
