"""scenario configuration tables

Revision ID: 942f647ae7ac
Revises: 8f0b3305e936
Create Date: 2026-08-10 18:43:00.490724

"""

import sqlalchemy as sa
from alembic import op

revision: str = "942f647ae7ac"
down_revision: str | None = "8f0b3305e936"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoring_policy_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("weights_json", sa.JSON(), nullable=False),
        sa.Column("penalties_json", sa.JSON(), nullable=False),
        sa.Column("stability_rule_json", sa.JSON(), nullable=False),
        sa.Column("reaction_rule_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scoring_policy_versions")),
        sa.UniqueConstraint("code", "version", name=op.f("uq_scoring_policy_versions_code_version")),
    )
    op.create_table(
        "scenario_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scenario_code", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("installation_version_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["installation_version_id"],
            ["installation_versions.id"],
            name=op.f("fk_scenario_versions_installation_version_id_installation_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario_versions")),
        sa.UniqueConstraint(
            "scenario_code", "version", name=op.f("uq_scenario_versions_scenario_code_version")
        ),
    )
    with op.batch_alter_table("scenario_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scenario_versions_installation_version_id"),
            ["installation_version_id"],
            unique=False,
        )

    op.create_table(
        "alarm_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scenario_version_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=64), nullable=False),
        sa.Column("equipment_code", sa.String(length=64), nullable=False),
        sa.Column("source_expression_json", sa.JSON(), nullable=False),
        sa.Column("activation_delay_ms", sa.Integer(), nullable=False),
        sa.Column("clear_expression_json", sa.JSON(), nullable=False),
        sa.Column("ack_required", sa.Boolean(), nullable=False),
        sa.Column("message_template", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_version_id"],
            ["scenario_versions.id"],
            name=op.f("fk_alarm_rules_scenario_version_id_scenario_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alarm_rules")),
        sa.UniqueConstraint(
            "scenario_version_id", "code", name=op.f("uq_alarm_rules_scenario_version_id_code")
        ),
    )
    with op.batch_alter_table("alarm_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alarm_rules_scenario_version_id"), ["scenario_version_id"], unique=False
        )

    op.create_table(
        "disturbance_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scenario_version_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("cause_code", sa.String(length=64), nullable=False),
        sa.Column("eligible_targets_json", sa.JSON(), nullable=False),
        sa.Column("onset_rule_json", sa.JSON(), nullable=False),
        sa.Column("development_rule_json", sa.JSON(), nullable=False),
        sa.Column("recovery_rule_json", sa.JSON(), nullable=False),
        sa.Column("hidden_config_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_version_id"],
            ["scenario_versions.id"],
            name=op.f("fk_disturbance_templates_scenario_version_id_scenario_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disturbance_templates")),
        sa.UniqueConstraint(
            "scenario_version_id", "code", name=op.f("uq_disturbance_templates_scenario_version_id_code")
        ),
    )
    with op.batch_alter_table("disturbance_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_disturbance_templates_scenario_version_id"), ["scenario_version_id"], unique=False
        )

    op.create_table(
        "expected_action_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scenario_version_id", sa.String(length=36), nullable=False),
        sa.Column("situation_code", sa.String(length=64), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("target_selector", sa.String(length=64), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("required_preconditions_json", sa.JSON(), nullable=False),
        sa.Column("valid_window_ms", sa.Integer(), nullable=False),
        sa.Column("expected_effect_json", sa.JSON(), nullable=False),
        sa.Column("verification_rule_json", sa.JSON(), nullable=False),
        sa.Column("criticality", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_version_id"],
            ["scenario_versions.id"],
            name=op.f("fk_expected_action_rules_scenario_version_id_scenario_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expected_action_rules")),
        sa.UniqueConstraint(
            "scenario_version_id",
            "situation_code",
            "action_type",
            name=op.f("uq_expected_action_rules_scenario_version_id_situation_code_action_type"),
        ),
    )
    with op.batch_alter_table("expected_action_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_expected_action_rules_scenario_version_id"), ["scenario_version_id"], unique=False
        )

    op.create_table(
        "scenario_levels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scenario_version_id", sa.String(length=36), nullable=False),
        sa.Column("level_no", sa.Integer(), nullable=False),
        sa.Column("sensor_delay_ms", sa.Integer(), nullable=False),
        sa.Column("nuisance_alarm_rate", sa.Float(), nullable=False),
        sa.Column("reaction_deadline_ms", sa.Integer(), nullable=False),
        sa.Column("development_speed_factor", sa.Float(), nullable=False),
        sa.Column("hints_enabled", sa.Boolean(), nullable=False),
        sa.Column("reserve_config_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_version_id"],
            ["scenario_versions.id"],
            name=op.f("fk_scenario_levels_scenario_version_id_scenario_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario_levels")),
        sa.UniqueConstraint(
            "scenario_version_id", "level_no", name=op.f("uq_scenario_levels_scenario_version_id_level_no")
        ),
    )
    with op.batch_alter_table("scenario_levels", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scenario_levels_scenario_version_id"), ["scenario_version_id"], unique=False
        )

    op.create_table(
        "scenario_stages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scenario_version_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("order_no", sa.Integer(), nullable=False),
        sa.Column("entry_rule_json", sa.JSON(), nullable=False),
        sa.Column("success_rule_json", sa.JSON(), nullable=False),
        sa.Column("failure_rule_json", sa.JSON(), nullable=False),
        sa.Column("timeout_ms", sa.Integer(), nullable=False),
        sa.Column("required_checks_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_version_id"],
            ["scenario_versions.id"],
            name=op.f("fk_scenario_stages_scenario_version_id_scenario_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario_stages")),
        sa.UniqueConstraint(
            "scenario_version_id", "code", name=op.f("uq_scenario_stages_scenario_version_id_code")
        ),
        sa.UniqueConstraint(
            "scenario_version_id", "order_no", name=op.f("uq_scenario_stages_scenario_version_id_order_no")
        ),
    )
    with op.batch_alter_table("scenario_stages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scenario_stages_scenario_version_id"), ["scenario_version_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scenario_stages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenario_stages_scenario_version_id"))

    op.drop_table("scenario_stages")
    with op.batch_alter_table("scenario_levels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenario_levels_scenario_version_id"))

    op.drop_table("scenario_levels")
    with op.batch_alter_table("expected_action_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expected_action_rules_scenario_version_id"))

    op.drop_table("expected_action_rules")
    with op.batch_alter_table("disturbance_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_disturbance_templates_scenario_version_id"))

    op.drop_table("disturbance_templates")
    with op.batch_alter_table("alarm_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alarm_rules_scenario_version_id"))

    op.drop_table("alarm_rules")
    with op.batch_alter_table("scenario_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenario_versions_installation_version_id"))

    op.drop_table("scenario_versions")
    op.drop_table("scoring_policy_versions")
    # ### end Alembic commands ###
