"""operator observations and diagnoses

Revision ID: 3f9ac5e34f47
Revises: a58dd63500a6
Create Date: 2026-08-12 14:29:54.741221

"""

import sqlalchemy as sa
from alembic import op

revision: str = "3f9ac5e34f47"
down_revision: str | None = "a58dd63500a6"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operator_diagnoses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("affected_area_code", sa.String(length=64), nullable=False),
        sa.Column("deviation_code", sa.String(length=64), nullable=False),
        sa.Column("suspected_cause_code", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_operator_diagnoses_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_diagnoses")),
        sa.UniqueConstraint("request_id", name=op.f("uq_operator_diagnoses_request_id")),
    )
    with op.batch_alter_table("operator_diagnoses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_operator_diagnoses_session_id"), ["session_id"], unique=False)
        batch_op.create_index(
            "ix_operator_diagnoses_session_sim_time", ["session_id", "sim_time_ms"], unique=False
        )

    op.create_table(
        "operator_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("sim_time_ms", sa.Integer(), nullable=False),
        sa.Column("observation_type", sa.String(length=64), nullable=False),
        sa.Column("target_code", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_operator_observations_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_observations")),
        sa.UniqueConstraint("request_id", name=op.f("uq_operator_observations_request_id")),
    )
    with op.batch_alter_table("operator_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_operator_observations_observation_type"), ["observation_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_operator_observations_session_id"), ["session_id"], unique=False)
        batch_op.create_index(
            "ix_operator_observations_session_sim_time", ["session_id", "sim_time_ms"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("operator_observations", schema=None) as batch_op:
        batch_op.drop_index("ix_operator_observations_session_sim_time")
        batch_op.drop_index(batch_op.f("ix_operator_observations_session_id"))
        batch_op.drop_index(batch_op.f("ix_operator_observations_observation_type"))

    op.drop_table("operator_observations")
    with op.batch_alter_table("operator_diagnoses", schema=None) as batch_op:
        batch_op.drop_index("ix_operator_diagnoses_session_sim_time")
        batch_op.drop_index(batch_op.f("ix_operator_diagnoses_session_id"))

    op.drop_table("operator_diagnoses")
    # ### end Alembic commands ###
